### PR TITLE
fun intro to socat, comic with permission from Julia Evans

### PR DESCRIPTION
**Pull request by ultrasaurus**
I've added to the socat narrative with examples inspired by included comic by @jvns

approval via Twitter DM:
image

Would like review by @carllerche for how I write up the copyright info -- Is README in static/img/external and (c) under the image sufficient?

And would be great if a volunteer would type in the socat commands to verify no typos!

Once we have our reviews complete, I'll ping Julia to see if she wants to look at / approve the preview before this gets merged

### CODE REVIEW

**Comment by carllerche** [comment]
The copyright / attribution strategy looks fine in my uneducated opinion (I am not a lawyer!)

**Comment by ultrasaurus** [comment]
for easy reference page content preview: https://deploy-preview-413--tokio.netlify.com/docs/network-utilities/socat/

README in folder where the image is on github, noting license is diff from rest of repo: https://github.com/tokio-rs/website/blob/5f1284d162d1731b5dd1bc9514a159dc05d0f63f/static/img/external/README.md

**Comment by ultrasaurus** [comment]
Julia reviewed via twitter ...
image

**Comment by ultrasaurus** [comment]
tagging @LucioFranco for review, but could be anyone on the team who has time to take a look at the content of this section

**Pull request merged**
