### PR TITLE
Update shortcodes

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Not quite sure the context for this PR, but wanted to let you know about alternate proposal for handling 0.1 docs, which would change the URLs --- https://github.com/tokio-rs/website/issues/371

**Comment by vorot93** [comment]
I don't quite get the contradiction. Your proposal is to deploy the docs as they were before 0.2. Mine is about the current doc.

**Comment by ultrasaurus** [comment]
I assumed we would remove 0.1 content from the current doc (or rather update so its about 0.2), so the 0.1 shortcodes would go to the 0.1 site (so wanted you to be aware of that potential change, which may or may not change how you would structure this)

**Comment by ultrasaurus** [comment]
Like I said, I don't really have context here.  If we're going to keep an archive of the 0.1 docs from an old commit hosted on a different subdomain, why would we also keep references to 0.1 doc in master branch?

**Comment by vorot93** [comment]
When it comes to outdated tutorial chapters we can do one of two things:
1. Rip them out and mark it as TODO, or
2. Keep it there and say that the API and examples are out of date but the general concepts still apply.

Like I said, there's no contradiction with your proposal. I'm personally in favour of # 2 - keep those old pages together with new ones as complementary theory reading.

**Comment by ultrasaurus** [comment]
adding label to indicate that there's an open question on this PR.  I just merged https://github.com/tokio-rs/website/pull/365 and it would be good to figure out what we want to do with orphaned pages.  I'd be in favor of #2 with an issue discussing what needs to be done (e.g. just update syntax or rewrite part/all and what needs to be better explained)

**Comment by vorot93** [comment]
In any case, this PR merely improves the shortcode handling throughout the website, so even if we decide to cut the pages later, it shouldn't be an obstacle to getting this merged.

**Comment by ultrasaurus** [comment]
@vorot93 what would you like to do with this?  Did my feedback make sense?  

I agree that it might have been good to leave old content with a banner or something to make clear what needed work, and I can see the logic of the current direction of focusing our efforts on a smaller amount of consistent docs that can grow.

**Comment by Darksonn** [comment]
Closing this as we are no longer using Hugo.

**Pull request closed without merging**
