### PR TITLE
Fix broken link to async/await with Hyper.

### PR DESCRIPTION
**Pull request by davidbarsky**
The link to the Hyper example with async/await was broken. This PR corrects that.

### CODE REVIEW

**Comment by carllerche** [comment]
I filed #215 to fix CI.

**Comment by carllerche** [comment]
Would you mind merging `master` to fix CI?

**Comment by davidbarsky** [comment]
@carllerche yep, will do before 5 PM on the east coast. Meetings day.

**Comment by davidbarsky** [comment]
Alright, merged, but didn't squash. I assume that'll happen on merge here.

**Comment by carllerche** [comment]
Yep 👍 thanks so much

**Pull request merged**
