### PR TITLE
Update getting_asynchronous.md

### PR DESCRIPTION
**Pull request by mathijshenquet**
I was reading the documentation yesterday and I thought this particular example was a bit hard to grok at first. I think it would be more clear to me if rewritten this way.

### CODE REVIEW

**Comment by carllerche** [comment]
I agree that it is confusing, unfortunately, the confusing bits are required to make the borrow checker happy.

That said, it could be that non lexical lifetimes fixes this. I'm not sure how to check.

**Comment by mathijshenquet** [comment]
I just checked: on rust 1.31.0 the above compiles.

**Comment by carllerche** [comment]
@mathijshenquet That makes sense as I believe that NLL is only enabled for the 2018 edition. Now, the question is how best to proceed. Should the docs use the 2018 edition for examples?

**Comment by carllerche** [comment]
I think the consensus is that the website should switch to use the 2018 edition. That probably should go in a separate PR to update the Ci script and any example that breaks. Any interest in taking a stab?

**Comment by carllerche** [comment]
Could you merge master? That should hopefully get CI to pass.

**Comment by ultrasaurus** [comment]
@mathijshenquet it looks like this didn't get update after Tokio moved to Rust 2018, and now more time has passed and this content would need to be changed once again (I think) for the changes in futures with Rust 1.39.0. In any case4, this page has been removed from the nav while we figure out how/whether to update the old content.  So, I'm going to close this PR.

If you want to do more work on this or tokio docs in general, please join us in the tokio-docs discord channel: https://discord.gg/tokio

**Pull request closed without merging**
