### PR TITLE
Add documentation on framed streams & codecs

### PR DESCRIPTION
**Pull request by sbstp**
[Rendered](https://github.com/sbstp/website/blob/frames/content/docs/going-deeper/frames.md)

This is a first draft of docs for framed streams and codecs.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks. Looks good to me. CI isn't passing though (CI checks the code snippets).

You can look at other guides for ideas on how to get the examples to pass. Sometimes it requires a bit of additional code to be hidden.

**Comment by sbstp** [comment]
I like the title but I don't like the description. I'll try come up with something better.

**Comment by sbstp** [comment]
All good now.

**Comment by carllerche** [comment]
Thanks!

**Pull request merged**
