### PR TITLE
Fixed the tense of a use of `pin`

### PR DESCRIPTION
**Pull request by hpux735**
Just a small grammatical change.

### CODE REVIEW

**Comment by Darksonn** [comment]
Hmm, this sentence may need a more general improvement. The issue is that, to call `.next()`, the `Stream` must either implement the `Unpin` trait, or it must be pinned. In this case, the stream does not implement the `Unpin` trait, and therefore we must pin it.

**Comment by hpux735** [comment]
I believe that's clear from the text, but the only problem is that the present tense `pin` is used, when the past-tense `pinned` should be used.  I also checked the documentation for `Pin` and using the past-tense `pinned` is appropriate when talking about types that are or were wrapped in `Pin`.

**Comment by hpux735** [comment]
here's the relevant section from the docs:

> At a high level, a Pin\<P\> ensures that the pointee of any pointer type P has a stable location in memory, meaning it cannot be moved elsewhere and its memory cannot be deallocated until it gets dropped. We say that the pointee is "pinned".

https://doc.rust-lang.org/std/pin/index.html

**Review by Darksonn — APPROVED** [review]
Right, I mean, the thing that confuses me about the sentence is that returning a pinned stream is an oxymoron because returning a value will move it, which is exactly what pinning prevents you from doing, so, like, _of course_ it doesn't return a pinned stream — that would be impossible.

But that said, it is indeed _correct_ that the returned stream is not pinned.

**Pull request merged**
