### PR TITLE
Update examples to 2018 edition

### PR DESCRIPTION
**Pull request by bIgBV**
I'm updating the examples as I go through them. To test weather or not this works, I ran the examples to test and ensured that everything ran as expected and no warnings were generated by the compiler.

### CODE REVIEW

**Comment by bIgBV** [comment]
I ran the ci `test.sh` script, but I'm not entirely sure what's causing the errors, since the examples work standalone.

**Comment by carllerche** [comment]
Does this command (in the ci script) have to be updated?

https://github.com/tokio-rs/website/blob/6a012bacfb88574a7be96f9f8e1261f8540843b8/ci/test.sh#L17

**Comment by carllerche** [comment]
PS, thanks for updating!

**Comment by bIgBV** [comment]
I'm not sure, if I understand the line correctly, it takes the passed in markdown file and then runs the rustc on it with the `test` flag, right? If that's the case it should work, but something seems to be missing.

**Comment by carllerche** [comment]
@bIgBV If `rust-skeptic` works, we can try switching to it!

**Comment by carllerche** [comment]
My guess is that the command does need to specify the crates to "extern". Without the explicit `extern` lines, how would it know which crates to link?

**Comment by bIgBV** [comment]
Yeah, that makes sense. I'll try to get `rust-skeptic` to work and hopefully, it can handle both the situations while the codebase is in transition. I think it should because I'm guessing it just somehow invoked `cargo-test` internally.

**Comment by ultrasaurus** [comment]
@bIgBV time has passed and now this content would need to be changed once again some of this has moved into the Rust language.  For now this page has been removed from the nav and I'm going to close this PR.

If you want to do more work on this or tokio docs in general, please join us in the tokio-docs discord channel: https://discord.gg/tokio

**Pull request closed without merging**
