### PR TITLE
Update spawning.md

### PR DESCRIPTION
**Pull request by linkwik**
Modify the Get and Set value types

### CODE REVIEW

**Review by Darksonn — COMMENTED** [review]
This changes the item type in the `HashMap` from `Bytes` to `Vec<u8>`. Can you elaborate on that?

**Comment by linkwik** [comment]
I see provide [source file](https://github.com/tokio-rs/website/blob/master/tutorial-code/spawning/src/main.rs ), we should remain consistent

**Comment by Darksonn** [comment]
Ah, I see. The `bytes` crate is not covered until the next chapter. Can you add the missing comments too?

**Comment by linkwik** [comment]
Of course, I added it.

**Review by Darksonn — APPROVED** [review]
Thank you for noticing the inconsistency between the two versions!

**Pull request merged**
