### PR TITLE
add rss feed generation and link on the website

### LINKED ISSUE #458: RSS feed link is returning 404
https://tokio.rs/blog/index.xml is no longer working

### PR DESCRIPTION
**Pull request by jxs**
Closes: #458

### CODE REVIEW

**Comment by carllerche** [comment]
Looks great. CI isn't passing though.

You may have to run `npm run build` locally to see what's happening.

**Comment by Darksonn** [comment]
GitHub doesn't pick up the "closes: #num" part if it's in the title.

**Comment by jxs** [comment]
`request` is not available on `next export`, so had to find another way, which is to generate the rss feed on build time.
Also added a redirect from the previous location `/blog/index.xml` to the new one

**Comment by carllerche** [comment]
I have no idea what is going on, but if it works, seems good to me :laughing:

**Pull request merged**
