### PR TITLE
Add a note on the async couchbase driver

### PR DESCRIPTION
**Pull request by daschl**
The couchbase SDK is future-driven from the ground up and fits very well into the tokio ecosystem. Here is an example: https://github.com/daschl/tokio-cb/blob/master/src/main.rs

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks! Looks like I just merged something though which created a rebase conflict, want to rebase?

**Comment by daschl** [comment]
@alexcrichton do you want me to squash into one commit or is it fine this way?

**Comment by alexcrichton** [comment]
Nah that's fine!

**Comment by daschl** [comment]
Thanks!

**Pull request merged**
