### PR TITLE
Update to use Bytes instead of Vec<u8>

### PR DESCRIPTION
**Pull request by sharedrory**
Otherwise having bytes as a dependency is pointless

### CODE REVIEW

**Comment by Darksonn** [comment]
Thanks. Are you able to update [`content/tokio/tutorial/channels.md`](https://github.com/tokio-rs/website/blob/master/content/tokio/tutorial/channels.md) as well?

**Comment by sharedrory** [comment]
Done! If I understand correctly, lines starting with # are hidden on the site?

**Comment by Darksonn** [comment]
Yes.

**Review by Darksonn — APPROVED** [review]
Thanks.

**Comment by Darksonn** [comment]
Can you open it as a new PR?

**Comment by Darksonn** [comment]
GitHub actions had some downtime earlier today. I'm guessing that this is the reason we missed it before merging.

**Comment by sharedrory** [comment]
Done! https://github.com/tokio-rs/website/pull/612

**Pull request merged**
