### PR TITLE
add tokio-zh(中文) website

### PR DESCRIPTION
**Pull request by krircc**
add [tokio-zh](https://tokio-zh.github.io/) website is ok? thanks

### CODE REVIEW

**Comment by krircc** [comment]
@carllerche  of course,  it should be in the one same site proper. I only not familiar with hugo,  I think it need some sttting befor I can add  the CN content.

**Comment by carllerche** [comment]
I'm working on restructuring the site. I can try to figure out how to carve out space for different translations.

**Comment by krircc** [comment]
@carllerche  :+1:  Thanks, I will add the content after you

**Comment by carllerche** [comment]
There was this guide: https://gohugo.io/content-management/multilingual/, but it wasn't 100% trivial. It wanted translations of everything (including the blog) and I didn't know how to fall back on English.

Lets not hold up the link, after #196 lands, could you update the PR to just point to https://tokio-zh.github.io/?

At some point in the future, I will investigate hugo's translation feature again.

**Comment by krircc** [comment]
@carllerche sure, there is a PR for it  #198

**Comment by krircc** [comment]
@carllerche now all the content  translationed to chinese at [tokio-zh](https://tokio-zh.github.io/) (with the #196 and blogs) , I also update a bit the website.

**Comment by carllerche** [comment]
Replaced by #207

**Pull request closed without merging**
