### PR TITLE
Import required trait into example

### PR DESCRIPTION
**Pull request by kanerogers**
This one tripped me a up a little bit. 😄

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think this is intended to be a snippet and/or standalone example though? Not necessarily entirely self contained?

**Comment by kanerogers** [comment]
You might be right! I was just following along at home, pasted it into my
editor and was surprised when the compiler got angry with me. Just my
feedback. 😊

**Comment by carllerche** [comment]
This guide has been removed, so I will close this. Thanks!

**Comment by kanerogers** [comment]
Awesome. PS. thanks for all your hard work on Tokio @alexcrichton and @carllerche - can't wait to see what comes out of the reform process. 😄

**Pull request closed without merging**
