### PR TITLE
.into -> Bytes::from

### PR DESCRIPTION
**Pull request by mvolkmann**
This implements a change suggested by Alice here: https://users.rust-lang.org/t/after-3-months-still-learning-to-read-rust-code/55616/12?u=mvolkmann

### CODE REVIEW

**Comment by mvolkmann** [comment]
@Darksonn I implemented the change you suggested.

**Comment by Darksonn** [comment]
Thanks! Would you be able to update [`tutorial-code/hello-tokio/src/main.rs`][1] too?

[1]: https://github.com/tokio-rs/website/blob/master/tutorial-code/hello-tokio/src/main.rs

**Comment by Darksonn** [comment]
Oops, I missed that you already did. You need to add `bytes` the `Cargo.toml` to fix the build.

**Comment by mvolkmann** [comment]
Okay, I added the `bytes` dependency.

**Review by Darksonn — APPROVED** [review]

**Comment by Darksonn** [comment]
Sorry, but I'm reverting this change. I would rather not be introducing the bytes crate as early as on the Hello Tokio page.

**Pull request merged**
